# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

complexity:
  LongMethod:
    threshold: 80
  TooManyFunctions:
    thresholdInFiles: 17
    thresholdInClasses: 17
  LongParameterList:
    functionThreshold: 7
  ComplexMethod:
    threshold: 25
formatting:
  Indentation:
    continuationIndentSize: 8
  ParameterListWrapping:
    indentSize: 8
style:
  ReturnCount:
    max: 5
  MagicNumber:
    ignoreEnums: true
